frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface eth1
 ip address 10.30.12.2/30
!
interface eth2
 ip address 10.30.23.1/30
!
interface lo
 ip address 2.2.2.2/32
!
router bgp 65001
 bgp router-id 2.2.2.2
 neighbor 10.30.12.1 remote-as 65001
 neighbor 10.30.23.2 remote-as 65001
 !
 address-family ipv4 unicast
  network 2.2.2.2/32
  neighbor 10.30.12.1 activate
  neighbor 10.30.23.2 activate
  neighbor 10.30.12.1 route-reflector-client
  neighbor 10.30.23.2 route-reflector-client
 exit-address-family
!
line vty
!
